USE SnakesAndLadder;
	drop procedure if exists DIAGNOSTIC;
DELIMITER //
CREATE PROCEDURE DIAGNOSTIC(IN Context VARCHAR(255))
BEGIN
	GET DIAGNOSTICS CONDITION 1
	@P1 = MYSQL_ERRNO, @P2 = MESSAGE_TEXT;
    
	SELECT Context, @P1 AS ERROR_NUM, @P2 AS MESSAGE;
END//
